services:
  # Base de datos MySQL para QA
  mysql-qa:
    image: mysql:8.0
    container_name: mysql-qa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: dockerapp_qa
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword123
    ports:
      - "3306:3306"
    volumes:
      # Volumen persistente para datos de MySQL QA
      - mysql_qa_data:/var/lib/mysql
      # Script de inicialización QA
      - ./init-qa.sql:/docker-entrypoint-initdb.d/init-qa.sql:ro

  # Base de datos MySQL para PROD
  mysql-prod:
    image: mysql:8.0
    container_name: mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword456
      MYSQL_DATABASE: dockerapp_prod
      MYSQL_USER: produser
      MYSQL_PASSWORD: prodpassword456
    ports:
      - "3307:3306"  # Puerto diferente para PROD
    volumes:
      # Volumen persistente para datos de MySQL PROD
      - mysql_prod_data:/var/lib/mysql
      # Script de inicialización PROD
      - ./init-prod.sql:/docker-entrypoint-initdb.d/init-prod.sql:ro

  # Aplicación en entorno QA
  app-qa:
    image: baltasarlopezv/tp02-docker-app:v1.6
    container_name: dockerapp-qa
    restart: always
    environment:
      - PORT=3000
      - ENVIRONMENT=QA
      - DB_HOST=mysql-qa
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=apppassword123
      - DB_NAME=dockerapp_qa
    ports:
      - "3000:3000"
    depends_on:
      - mysql-qa
    labels:
      - "environment=qa"
      - "app=dockerapp"

  # Aplicación en entorno PROD
  app-prod:
    image: baltasarlopezv/tp02-docker-app:v1.6
    container_name: dockerapp-prod
    restart: always
    environment:
      - PORT=3000
      - ENVIRONMENT=PROD
      - DB_HOST=mysql-prod
      - DB_PORT=3306
      - DB_USER=produser
      - DB_PASSWORD=prodpassword456
      - DB_NAME=dockerapp_prod
    ports:
      - "3001:3000"  # Puerto externo 3001, interno 3000
    depends_on:
      - mysql-prod
    labels:
      - "environment=prod"
      - "app=dockerapp"

# Volúmenes persistentes
volumes:
  mysql_qa_data:
    driver: local
  mysql_prod_data:
    driver: local
